require_relative 'extensions/string'
require_relative 'cuties_in_denver/twit'
require_relative 'cuties_in_denver/pet'
require_relative 'cuties_in_denver/adopt_a_pet'
require_relative 'cuties_in_denver/greeting'